INFO 2025-10-16 10:06:29,876 autoreload 4961 4805170688 Watching for file changes with StatReloader
WARNING 2025-10-16 10:06:37,340 log 4961 123145490186240 Not Found: /World FX CO LTD_files/googlelogo_color_42x16dp.png
WARNING 2025-10-16 10:06:38,088 log 4961 123145490186240 Not Found: /gtranslate.net/flags/24.png
WARNING 2025-10-16 10:06:51,408 log 4961 123145423028224 Not Found: /signup/World FX CO LTD_files/googlelogo_color_42x16dp.png
WARNING 2025-10-16 10:06:51,532 log 4961 123145423028224 Not Found: /signup/gtranslate.net/flags/24.png
WARNING 2025-10-16 10:07:48,073 log 4961 123145473396736 Not Found: /terms-and-conditions/Rules _ World Fx _ The New generation Crypto investment Platform_files/chat.html
WARNING 2025-10-16 10:07:48,076 log 4961 123145456607232 Not Found: /terms-and-conditions/Rules _ World Fx _ The New generation Crypto investment Platform_files/ER-LRTICKER.html
WARNING 2025-10-16 10:08:09,760 log 4961 123145423028224 Not Found: /login/World FX CO LTD_files/googlelogo_color_42x16dp.png
WARNING 2025-10-16 10:08:09,840 log 4961 123145423028224 Not Found: /login/gtranslate.net/flags/24.png
WARNING 2025-10-16 10:08:10,028 log 4961 123145456607232 Not Found: /login/er.lrticker.html
INFO 2025-10-16 10:13:54,450 autoreload 5802 4486280704 Watching for file changes with StatReloader
WARNING 2025-10-16 10:13:57,880 log 5802 123145370304512 Not Found: /signup/World FX CO LTD_files/googlelogo_color_42x16dp.png
WARNING 2025-10-16 10:13:58,057 log 5802 123145370304512 Not Found: /signup/gtranslate.net/flags/24.png
WARNING 2025-10-16 10:14:09,743 log 5802 123145370304512 Not Found: /signup/World FX CO LTD_files/googlelogo_color_42x16dp.png
WARNING 2025-10-16 10:14:09,796 log 5802 123145370304512 Not Found: /signup/gtranslate.net/flags/24.png
ERROR 2025-10-16 10:16:04,572 views 5802 123145370304512 Error creating user: table custom_users has no column named country_id
WARNING 2025-10-16 10:16:05,091 log 5802 123145370304512 Not Found: /signup/World FX CO LTD_files/googlelogo_color_42x16dp.png
WARNING 2025-10-16 10:16:05,156 log 5802 123145370304512 Not Found: /signup/gtranslate.net/flags/24.png
WARNING 2025-10-16 10:16:15,966 log 5802 123145370304512 Not Found: /login/World FX CO LTD_files/googlelogo_color_42x16dp.png
WARNING 2025-10-16 10:16:16,027 log 5802 123145370304512 Not Found: /login/gtranslate.net/flags/24.png
WARNING 2025-10-16 10:16:16,098 log 5802 123145370304512 Not Found: /login/er.lrticker.html
ERROR 2025-10-16 10:16:26,725 views 5802 123145370304512 Login error for email gabby@gmail.com: no such column: custom_users.country_id
WARNING 2025-10-16 10:16:26,976 log 5802 123145370304512 Not Found: /login/World FX CO LTD_files/googlelogo_color_42x16dp.png
WARNING 2025-10-16 10:16:27,008 log 5802 123145370304512 Not Found: /login/gtranslate.net/flags/24.png
WARNING 2025-10-16 10:16:27,079 log 5802 123145370304512 Not Found: /login/er.lrticker.html
WARNING 2025-10-16 10:16:39,911 log 5802 123145437462528 Not Found: /favicon.ico
ERROR 2025-10-16 10:16:48,515 log 5802 123145437462528 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: custom_users.country_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/decorators/debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/contrib/auth/views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/generic/edit.py", line 150, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/forms/forms.py", line 206, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/forms/forms.py", line 201, in errors
    self.full_clean()
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/forms/forms.py", line 338, in full_clean
    self._clean_form()
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/forms/forms.py", line 354, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/decorators/debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/contrib/auth/forms.py", line 366, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/decorators/debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 114, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 65, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: custom_users.country_id
INFO 2025-10-16 11:35:51,861 autoreload 8206 4702291456 Watching for file changes with StatReloader
ERROR 2025-10-16 11:35:55,753 log 8206 123145576628224 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: custom_users.country_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 449, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/decorators/debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/contrib/auth/views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/generic/edit.py", line 150, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/forms/forms.py", line 206, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/forms/forms.py", line 201, in errors
    self.full_clean()
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/forms/forms.py", line 338, in full_clean
    self._clean_form()
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/forms/forms.py", line 354, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/decorators/debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/contrib/auth/forms.py", line 366, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/views/decorators/debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 114, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 65, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: custom_users.country_id
INFO 2025-10-16 11:47:13,785 autoreload 9590 4444075520 Watching for file changes with StatReloader
INFO 2025-10-16 11:48:37,328 autoreload 9781 4563965440 Watching for file changes with StatReloader
WARNING 2025-10-16 11:51:16,891 log 9781 123145527447552 Not Found: /register
WARNING 2025-10-16 11:51:22,297 log 9781 123145527447552 Not Found: /World FX CO LTD_files/googlelogo_color_42x16dp.png
WARNING 2025-10-16 11:51:24,507 log 9781 123145544237056 Not Found: /signup/World FX CO LTD_files/googlelogo_color_42x16dp.png
WARNING 2025-10-16 11:51:24,559 log 9781 123145544237056 Not Found: /signup/gtranslate.net/flags/24.png
ERROR 2025-10-16 11:52:35,773 email_service 9781 123145527447552 Failed to send welcome email to sandy@gmail.com: 'Settings' object has no attribute 'SUPPORT_EMAIL'
ERROR 2025-10-16 11:52:35,823 log 9781 123145527447552 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/venex_app/views.py", line 214, in dashboard
    return render(request, 'dashboard.html', {'user': request.user})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: dashboard.html
INFO 2025-10-16 11:57:10,609 autoreload 9781 4563965440 /Users/emmidev/Desktop/Projects/RBC/venex_app/views.py changed, reloading.
INFO 2025-10-16 11:57:12,204 autoreload 9874 4770006528 Watching for file changes with StatReloader
INFO 2025-10-16 11:57:33,668 autoreload 9874 4770006528 /Users/emmidev/Desktop/Projects/RBC/venex_app/views.py changed, reloading.
INFO 2025-10-16 11:57:34,282 autoreload 9884 4509218304 Watching for file changes with StatReloader
INFO 2025-10-16 11:58:02,102 autoreload 9884 4509218304 /Users/emmidev/Desktop/Projects/RBC/venex_app/views.py changed, reloading.
INFO 2025-10-16 11:58:03,163 autoreload 9896 4640798208 Watching for file changes with StatReloader
INFO 2025-10-16 12:00:50,353 autoreload 9896 4640798208 /Users/emmidev/Desktop/Projects/RBC/venex_app/views.py changed, reloading.
INFO 2025-10-16 12:00:51,195 autoreload 9971 4687164928 Watching for file changes with StatReloader
ERROR 2025-10-16 12:01:09,888 log 9971 123145578594304 Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/venex_app/views.py", line 214, in dashboard
    return render(request, 'jobs/dashboard.html', {'user': request.user})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emmidev/Desktop/Projects/RBC/.venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: jobs/dashboard.html
INFO 2025-10-16 12:01:33,180 autoreload 9971 4687164928 /Users/emmidev/Desktop/Projects/RBC/venex_app/views.py changed, reloading.
INFO 2025-10-16 12:01:34,609 autoreload 10026 4799104512 Watching for file changes with StatReloader
INFO 2025-10-16 12:01:36,124 autoreload 10026 4799104512 /Users/emmidev/Desktop/Projects/RBC/venex_app/views.py changed, reloading.
INFO 2025-10-16 12:01:36,885 autoreload 10030 4619683328 Watching for file changes with StatReloader
INFO 2025-10-16 12:01:48,883 autoreload 10030 4619683328 /Users/emmidev/Desktop/Projects/RBC/venex_app/views.py changed, reloading.
INFO 2025-10-16 12:01:49,820 autoreload 10042 4488750592 Watching for file changes with StatReloader
INFO 2025-10-16 12:02:14,316 autoreload 10042 4488750592 /Users/emmidev/Desktop/Projects/RBC/venex_app/views.py changed, reloading.
INFO 2025-10-16 12:02:15,167 autoreload 10057 4609848832 Watching for file changes with StatReloader
INFO 2025-10-16 12:02:20,132 autoreload 10057 4609848832 /Users/emmidev/Desktop/Projects/RBC/venex_app/views.py changed, reloading.
INFO 2025-10-16 12:02:20,953 autoreload 10067 4623349248 Watching for file changes with StatReloader
WARNING 2025-10-16 12:02:24,056 log 10067 123145618690048 Not Found: /dashboard/resource.html
WARNING 2025-10-16 12:02:24,059 log 10067 123145635479552 Not Found: /dashboard/resource(2).html
WARNING 2025-10-16 12:02:24,071 log 10067 123145601900544 Not Found: /dashboard/resource(1).html
WARNING 2025-10-16 12:02:24,073 log 10067 123145685848064 Not Found: /dashboard/resource(3).html
WARNING 2025-10-16 12:02:24,110 log 10067 123145669058560 Not Found: /dashboard/img/user_2.png
WARNING 2025-10-16 12:02:51,246 log 10067 123145585111040 Not Found: /World FX CO LTD_files/googlelogo_color_42x16dp.png
WARNING 2025-10-16 12:02:51,355 log 10067 123145585111040 Not Found: /gtranslate.net/flags/24.png
WARNING 2025-10-16 12:03:34,152 log 10067 123145601900544 Not Found: /signup/World FX CO LTD_files/googlelogo_color_42x16dp.png
WARNING 2025-10-16 12:03:34,361 log 10067 123145601900544 Not Found: /signup/gtranslate.net/flags/24.png
WARNING 2025-10-16 12:03:38,454 log 10067 123145585111040 Not Found: /login/World FX CO LTD_files/googlelogo_color_42x16dp.png
WARNING 2025-10-16 12:03:38,742 log 10067 123145585111040 Not Found: /login/gtranslate.net/flags/24.png
WARNING 2025-10-16 12:03:38,765 log 10067 123145601900544 Not Found: /login/er.lrticker.html
WARNING 2025-10-16 12:03:49,535 log 10067 123145601900544 Not Found: /dashboard/img/user_2.png
WARNING 2025-10-16 12:03:49,629 log 10067 123145618690048 Not Found: /dashboard/resource.html
WARNING 2025-10-16 12:03:49,646 log 10067 123145635479552 Not Found: /dashboard/resource(1).html
WARNING 2025-10-16 12:03:49,678 log 10067 123145652269056 Not Found: /dashboard/resource(3).html
WARNING 2025-10-16 12:03:49,700 log 10067 123145585111040 Not Found: /dashboard/resource(2).html
